import json
import datetime
import os
from google.cloud import storage
from google.antigravity.types import Text

BUCKET_NAME = os.environ.get("TRIAGE_DEBUG_LOGS_BUCKET")

def upload_to_bucket(repository: str, issue_number: str | int, payload: str) -> None:
    """
    Uploads a string payload directly to the triage debug logs GCS bucket.
    """
    if not payload or not BUCKET_NAME:
        if not BUCKET_NAME:
            print("[LOGIC] Warning: Missing TRIAGE_DEBUG_LOGS_BUCKET, skipping GCS upload.")
        return
    try:
        storage_client = storage.Client()
        bucket = storage_client.bucket(BUCKET_NAME)
        
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_repo = str(repository).replace("/", "_") if repository else "unknown"
        blob_name = f"{safe_repo}/issue_{issue_number}_{timestamp}_debug.log"
        
        blob = bucket.blob(blob_name)
        blob.upload_from_string(payload, content_type="text/plain")
        print(f"[LOGIC] Uploaded debug logs to gs://{BUCKET_NAME}/{blob_name}")
    except Exception as e:
        print(f"[LOGIC] Error uploading debug logs to GCS: {e}")

def format_debug_trajectory(resolved_chunks: list) -> str:
    """
    Formats Antigravity Agent resolved stream chunks (thoughts, tool calls,
    tool outputs) into a structured, human-readable JSON string.
    """
    if not resolved_chunks:
        return "[]"
    serializable = []
    for chunk in resolved_chunks:
        try:
            dumped = chunk.model_dump()
        except AttributeError:
            dumped = chunk.dict()
        dumped["chunk_type"] = chunk.__class__.__name__
        serializable.append(dumped)
    return json.dumps(serializable, indent=2, default=str)


def save_local_agent_run_logs(issue_number: str | int, resolved_chunks: list, output_dir: str = None) -> str:
    """
    Serializes resolved stream chunks to JSON and saves them to local disk under target output_dir
    or falls back to evals/triage/results/logs/. Used for local evaluation runs and debugging.
    """
    if not resolved_chunks:
        return ""
    try:
        debug_log_str = format_debug_trajectory(resolved_chunks)
        
        if not output_dir:
            project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
            output_dir = os.environ.get("LOCAL_LOG_DIR", os.path.join(project_root, "evals", "triage", "results", "logs"))
            
        os.makedirs(output_dir, exist_ok=True)
        
        log_path = os.path.join(output_dir, f"gemini_cli_{issue_number}_debug.json")
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(debug_log_str)
            
        print(f"[LOGIC] 📄 Saved local agent trajectory log to: {log_path}")
        return log_path
    except Exception as e:
        print(f"[LOGIC] Error saving local agent debug log: {e}")
        return ""


def upload_agent_run_logs(repository: str, issue_number: str | int, resolved_chunks: list) -> None:
    """
    Serializes the Antigravity Agent resolved stream chunks to JSON and uploads them to GCS.
    """
    if not resolved_chunks:
        return
    try:
        debug_log_str = format_debug_trajectory(resolved_chunks)
        upload_to_bucket(repository, issue_number, debug_log_str)
    except Exception as e:
        print(f"[LOGIC] Error serializing/uploading agent debug logs: {e}")

def extract_final_output(resolved_chunks: list) -> str:
    """
    Extracts the final response text generated by the agent during the last execution step.
    
    Since the agent outputs conversational planning text during its tool-calling turns,
    this function isolates the final turn (highest step_index) and filters for text chunks,
    stripping away any intermediate planning text, thoughts, or markdown backticks around the JSON.
    """
    if not resolved_chunks:
        return ""
    # Filter for Text chunks (skip Thought and ToolCall chunks)
    text_chunks = [c for c in resolved_chunks if isinstance(c, Text)]
    if not text_chunks:
        return ""
    
    # Final output is in the last step
    last_step = text_chunks[-1].step_index
    return "".join(c.text for c in text_chunks if c.step_index == last_step).strip()